apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-video-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-video-service
  template:
    metadata:
      labels:
        app: mongo-video-service
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-video-service
spec:
  selector:
    app: mongo-video-service
  ports:
    - port: 27017
      targetPort: 27017
