apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  username: root
  password: example
  connectionString: mongodb://root:example@mongo-video-service:27017

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
stringData:
  username: admin
  password: admin
