name: Build and Push Docker images to Amazon ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Create ECR repositories if not exist
      run: |
        aws ecr describe-repositories --repository-names servicopagamentos-repo || aws ecr create-repository --repository-name servicopagamentos-repo
        aws ecr describe-repositories --repository-names servicopagamentos-worker || aws ecr create-repository --repository-name servicopagamentos-worker

    - name: Build API image
      run: |
        docker build -f Api/Dockerfile -t servicopagamentos:${{ env.IMAGE_TAG }} .

    - name: Tag and Push API image
      run: |
        docker tag servicopagamentos:${{ env.IMAGE_TAG }} 100527548163.dkr.ecr.us-east-1.amazonaws.com/servicopagamentos-repo:${{ env.IMAGE_TAG }}
        docker push 100527548163.dkr.ecr.us-east-1.amazonaws.com/servicopagamentos-repo:${{ env.IMAGE_TAG }}

    - name: Build Worker image
      run: |
        docker build -f Worker/Dockerfile -t servicopagamentos-worker:${{ env.IMAGE_TAG }} .

    - name: Tag and Push Worker image
      run: |
        docker tag servicopagamentos-worker:${{ env.IMAGE_TAG }} 100527548163.dkr.ecr.us-east-1.amazonaws.com/servicopagamentos-worker:${{ env.IMAGE_TAG }}
        docker push 100527548163.dkr.ecr.us-east-1.amazonaws.com/servicopagamentos-worker:${{ env.IMAGE_TAG }}
